name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        meteorRelease:
          # Meteor 3 Alpha
          - '--release 3.0-alpha.16'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install Dependencies
        run: |
          curl https://install.meteor.com | /bin/sh
          npm i -g @zodern/mtest

      - name: Run Tests
        run: |
          # Fix using old versions of Meteor
          export NODE_TLS_REJECT_UNAUTHORIZED=0

          mtest --package ./ --once ${{ matrix.meteorRelease }}
