name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        meteorRelease:
          - 3.0-alpha.16
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install Dependencies
        run: |
          curl https://install.meteor.com | /bin/sh

      - name: Run Tests
        run: |
          # Fix using old versions of Meteor
          export NODE_TLS_REJECT_UNAUTHORIZED=0  
          export NODE_OPTIONS="--trace-warnings --trace-uncaught"
          export FORCE_COLOR=true

          meteor test-packages ./ --raw-logs --exclude-archs="web.browser.legacy,web.cordova" --driver-package=test-in-console --release=${{ matrix.meteorRelease }}
