name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        meteorRelease:
          # Meteor 3 Alpha
          - '--release 3.0-alpha.17'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: 18
        run: npm ci

      - name: Install Dependencies
        run: |
          curl https://install.meteor.com | /bin/sh
          npm i -g @zodern/mtest

      - name: Run Tests
        run: |
          mtest --package ./ --once ${{ matrix.meteorRelease }}
